Name: Supreeth Hassan Ravindra,
CWID: 20020533,
Homework #3 - Problem 4 Part 2

In [1]:
#Importing the required libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, precision_score, recall_score, f1_score

In [2]:
# Loading the test and train data
test_data = pd.read_csv("test.csv")
train_data = pd.read_csv("train.csv")

In [3]:
train_data

x         y         z  class
0    8.599291  9.729418  6.432371      1
1    6.592955  0.082556  1.969544      1
2    5.596471  9.815682  0.027295      1
3    2.743639  8.783177  4.041946      0
4    4.458362  5.750222  0.099070      0
..        ...       ...       ...    ...
995  4.617314  7.700236  5.907128      0
996  5.453472  1.798360  1.992616      0
997  2.553853  8.122934  3.970146      0
998  3.210456  3.342092  7.831479      0
999  6.930237  2.742352  4.678527      1

[1000 rows x 4 columns]

In [4]:
test_data=test_data.drop("ID",axis=1)
test_data

x         y         z  actual-class
0   8.074807  5.988044  3.844979             1
1   4.952249  5.823205  1.612045             0
2   4.773178  0.078757  4.209442             0
3   9.845919  2.055448  3.525702             1
4   1.612492  1.320515  8.200455             0
5   7.987555  9.188111  7.222228             1
6   0.311558  3.974680  7.897371             0
7   1.219113  0.266045  2.741136             0
8   0.636340  1.831257  6.767459             0
9   0.890168  8.613714  2.884227             0
10  7.226514  9.852794  7.373560             1
11  2.709551  3.719191  5.743540             0
12  2.842368  1.902145  2.216614             0
13  3.610773  4.589548  7.714008             0
14  4.888200  6.720637  7.261562             0
15  8.857224  9.056900  8.862604             1
16  8.239402  9.347802  5.277351             1
17  3.219759  2.980960  6.646886             0
18  2.146974  5.328725  5.801703             0
19  1.156302  8.542813  1.859447             0

In [5]:
# Separate features and labels of both the test and train data
X_test = test_data.iloc[:, :-1].values  # Features
y_test = test_data.iloc[:, 3].values   # True labels

X_train = train_data.iloc[:, :-1].values  # Features
y_train = train_data.iloc[:, 3].values   # True labels

In [6]:
#Standardizing the data
scaler=StandardScaler()

X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

In [7]:
X_train

array([[ 1.2909373 ,  1.64214887,  0.49931501],
       [ 0.58765781, -1.74022951, -1.04276611],
       [ 0.23836075,  1.6723947 , -1.71388907],
       ...,
       [-0.82816586,  1.07888402, -0.35147993],
       [-0.59800699, -0.59737263,  0.98276143],
       [ 0.70588507, -0.80765324, -0.10670655]])

In [8]:
X_test

array([[ 1.26145444,  0.29221915, -0.67587323],
       [ 0.22890208,  0.24036738, -1.65704816],
       [ 0.16968773, -1.56660221, -0.51572457],
       [ 1.84711708, -0.94481538, -0.81616701],
       [-0.87547235, -1.1759955 ,  1.23796833],
       [ 1.23260235,  1.29882984,  0.80812488],
       [-1.30565881, -0.34110328,  1.10478984],
       [-1.00555311, -1.50768875, -1.16091351],
       [-1.19826158, -1.01533704,  0.60829464],
       [-1.11432691,  1.11814822, -1.09803775],
       [ 0.98094505,  1.50791231,  0.87462209],
       [-0.51270217, -0.42146964,  0.15837406],
       [-0.46878318, -0.99303838, -1.39139417],
       [-0.21469048, -0.14769089,  1.02421817],
       [ 0.20772271,  0.52266294,  0.82540858],
       [ 1.52018035,  1.25755631,  1.52892355],
       [ 1.31588183,  1.34906234, -0.04647421],
       [-0.34398925, -0.65368704,  0.55531384],
       [-0.69873258,  0.08482408,  0.18393164],
       [-1.02632319,  1.09584556, -1.548337  ]])

Answer: 1) Classifying using 3-nearest neighbors

In [9]:
classifier = KNeighborsClassifier(n_neighbors=3)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

print("Predicted values for y_test: \n", y_pred)
print("\nActual values for y_test: \n", y_test)
print("\nConfusion matrix for the above prediction: \n", confusion_matrix(y_test, y_pred))
print("\nClassification report the above prediction: \n", classification_report(y_test,y_pred)) 

Predicted values for y_test: 
 [1 1 0 1 0 1 0 0 0 0 1 0 0 0 1 1 1 0 0 0]

Actual values for y_test: 
 [1 0 0 1 0 1 0 0 0 0 1 0 0 0 0 1 1 0 0 0]

Confusion matrix for the above prediction: 
 [[12  2]
 [ 0  6]]

Classification report the above prediction: 
               precision    recall  f1-score   support

           0       1.00      0.86      0.92        14
           1       0.75      1.00      0.86         6

    accuracy                           0.90        20
   macro avg       0.88      0.93      0.89        20
weighted avg       0.93      0.90      0.90        20



Answer 2) Classifying using Euclidean distance weighted 3-nearest neighbors

In [10]:
classifier_weighted = KNeighborsClassifier(n_neighbors=3, metric="euclidean",weights="distance")
classifier_weighted.fit(X_train, y_train)
y_pred_weighted = classifier_weighted.predict(X_test)

print("Predicted values for y_test: \n", y_pred_weighted)
print("\nActual values for y_test: \n", y_test)
print("\nConfusion matrix for the above prediction: \n", confusion_matrix(y_test, y_pred_weighted))
print("\nClassification report the above prediction: \n", classification_report(y_test,y_pred_weighted)) 

Predicted values for y_test: 
 [1 1 0 1 0 1 0 0 0 0 1 0 0 0 1 1 1 0 0 0]

Actual values for y_test: 
 [1 0 0 1 0 1 0 0 0 0 1 0 0 0 0 1 1 0 0 0]

Confusion matrix for the above prediction: 
 [[12  2]
 [ 0  6]]

Classification report the above prediction: 
               precision    recall  f1-score   support

           0       1.00      0.86      0.92        14
           1       0.75      1.00      0.86         6

    accuracy                           0.90        20
   macro avg       0.88      0.93      0.89        20
weighted avg       0.93      0.90      0.90        20



From above we can see that, both "3-nearest neighbors" and "weighted 3-
nearest neighbors" classify the test data with the same results. Hence, for the given input (data and the value of k) both the models are giving the results. However, if we increase the amount of data and change the value of "K", we might see that, "weighted 3- nearest neighbors" will work better.